### ISSUE TITLE
Problems in the new version of gdccdated

### ISSUE THREAD

**Issue by papaloredsxd** [xBZZZZ/gdccdated#4]
ungzip error:
TypeError: The encoded data was not valid.

**Comment by xBZZZZ** [comment]
> TypeError: The encoded data was not valid.

That means unencoded save file (XML) is not valid UTF-8, that never happened to me.

Tell me which version and os (android or windows) of Geometry Dash generated the file and file name (`CCGameManager.dat` or `CCLocalLevels.dat`).

Compress the file to zip and attach zip, unless file is `CCGameManager.dat` and you are logged in and you don't want other people use your Geometry Dash account.

**Comment by papaloredsxd** [comment]
**"> > TypeError: The encoded data was not valid.
> 
> That means unencoded save file (XML) is not valid UTF-8, that never happened to me.
> 
> Tell me which version and os (android or windows) of Geometry Dash generated the file and file name (`CCGameManager.dat` or `CCLocalLevels.dat`).
> 
> Compress the file to zip and attach zip, unless file is `CCGameManager.dat` and you are logged in and you don't want other people use your Geometry Dash account."_**

@xBZZZZ 

You're wrong, that's not it. It literally doesn't work. When I try an older version of gdccdated it works but in the current version of gdccdated it doesn't work.

**Comment by papaloredsxd** [comment]
> > TypeError: The encoded data was not valid.
> 
> That means unencoded save file (XML) is not valid UTF-8, that never happened to me.
> 
> Tell me which version and os (android or windows) of Geometry Dash generated the file and file name (`CCGameManager.dat` or `CCLocalLevels.dat`).
> 
> Compress the file to zip and attach zip, unless file is `CCGameManager.dat` and you are logged in and you don't want other people use your Geometry Dash account.

@xBZZZZ

You're wrong, that's not it. It literally doesn't work. When I try an older version of gdccdated it works but in the current version of gdccdated it doesn't work.

**Comment by xBZZZZ** [comment]
> When I try an older version of gdccdated it works but in the current version of gdccdated it doesn't work.

That's because older gdccdated used lossy UTF-8 parser that handles errors by emitting U+FFFD (`�`).
Newer gdccdated uses strict UTF-8 parser that handles errors by giving up.

Also why don't you send the not working save file? (my save files work (android, gd 2.2.13))

**Comment by papaloredsxd** [comment]
> > When I try an older version of gdccdated it works but in the current version of gdccdated it doesn't work.
> 
> That's because older gdccdated used lossy UTF-8 parser that handles errors by emitting U+FFFD (`�`). Newer gdccdated uses strict UTF-8 parser that handles errors by giving up.
> 
> Also why don't you send the not working save file? (my save files work (android, gd 2.2.13))

The ccgamemanager.dat of the gd 2.2 does not work in the lastest version of gdccadated but the ccgamenaager.dat of the gd 2.1 does work in the latest version of gdccadated, you should try to return the gdccadated to a previous version

**Comment by xBZZZZ** [comment]
try now

**Comment by papaloredsxd** [comment]
> try now

bad UTF-8
code point offset inside data:	2823548
error offset inside code point:	0
data length:

**Comment by papaloredsxd** [comment]
Error bad UTF-8code point offset inside data:2823548error offset inside
code point:0data length:

**Comment by papaloredsxd** [comment]
downgrade the version of gdccdated to this version
https://github.com/xBZZZZ/gdccdated/tree/7fc58401788a1e6d2b491a40e0a142113004a22b

**Comment by papaloredsxd** [comment]
downgrade the version of gdccdated to this version
https://github.com/xBZZZZ/gdccdated/tree/7fc58401788a1e6d2b491a40e0a142113004a22b

**Comment by xBZZZZ** [comment]
<blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2017010829">bad UTF-8<br/>code point offset inside data:	2823548<br/>error offset inside code point:	0<br/>data length:</blockquote><table border="3"><tr><td width="480" height="82" valign="top" align="center"><h3>click <code>replace errors</code> to behave like old gdccdated</h3></td></tr></table>but beware that saving will not keep broken UTF-8 (like old gdccdated)<hr>also, is <code>data length:</code> actually empty for you or just copy+paste skill issue?

**Comment by papaloredsxd** [comment]
please downgrade the version of gdccdated to that version that I already
told you
https://github.com/xBZZZZ/gdccdated/tree/7fc58401788a1e6d2b491a40e0a142113004a22b

**Comment by xBZZZZ** [comment]
> please downgrade the version of gdccdated to that version that I already told you
> https://github.com/xBZZZZ/gdccdated/tree/7fc58401788a1e6d2b491a40e0a142113004a22b

why? does `replace errors` not behave like old version for you?
also why so old version? why not 642294321d01b6089ed70b4962bd98ded58e05db (version <strong>before</strong> UTF-8 to js string (UTF-16) converter changes)?

**Comment by papaloredsxd** [comment]
Did you forget when I told you the reason?

**Comment by xBZZZZ** [comment]
<table border="3"><tr><td><h2>ANSWER THIS FIRST:</h2></td><td>does <code>replace errors</code> not behave like old gdccdated for you?</td></tr></table><details><summary><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2023716753">Did you forget when I told you the reason?</blockquote></summary>I think I found reason:<ul><li><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2013449541">The ccgamemanager.dat of the gd 2.2 does not work in the lastest version of gdccadated but the ccgamenaager.dat of the gd 2.1 does work in the latest version of gdccadated, you should try to return the gdccadated to a previous version</blockquote></li></ul>but that reason is outdated since e83b87fb6d64510efdb47aa247e27004cb1a4fa1 unless <code>replace errors</code> doesn't behave like old gdccdated</details>

**Comment by papaloredsxd** [comment]
Yes, Please now downgrade the version of GDCCADATED to this version
https://github.com/xBZZZZ/gdccdated/tree/7fc58401788a1e6d2b491a40e0a142113004a22b

**Comment by xBZZZZ** [comment]
> Yes

what happens when you click `replace errors` button in new gdccdated?

**Comment by papaloredsxd** [comment]
When I click on the "replace errors" button the file does load

**Comment by papaloredsxd** [comment]
ccgamemanager.dat of the 1.9 does not load in gdccdated "xml parse error:
Error: tag name is not <k> but <key>", I want you to add compatibility to
the ccgamemanager.dat of the 1.9 in gdccdated

**Comment by xBZZZZ** [comment]
is this correct?:<ul><li><strong>both</strong> old gdccdated (642294321d01b6089ed70b4962bd98ded58e05db (before UTF-8 strict)) and new gdccdated (e83b87fb6d64510efdb47aa247e27004cb1a4fa1) with <code>replace errors</code> can load file but there is difference</li></ul><hr><details><summary>reasons for asking (click to expand)</summary><table>
<tr><th scope="col">who</th><th scope="col">says what (not full text)</th></tr>
<tr><td>@papaloredsxd</td><td><a href="#issuecomment-2010944030"><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2010944030">When I try an older version of gdccdated it works</blockquote></a></td></tr>
<tr><td>@xBZZZZ</td><td><a href="#issuecomment-2023815621"><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2023815621">does <code>replace errors</code> not behave like old gdccdated for you?</blockquote></a></td></tr>
<tr><td>@papaloredsxd</td><td><a href="#issuecomment-2023978651"><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2023978651">Yes</blockquote></a></td></tr>
<tr><td>@xBZZZZ</td><td><a href="#issuecomment-2023994860"><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2023994860">what happens when you click <code>replace errors</code> button in new gdccdated?</blockquote></a></td></tr>
<tr><td>@papaloredsxd</td><td><a href="#issuecomment-2024130202"><blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2024130202">When I click on the "replace errors" button the file does load</blockquote></a></td></tr>
</table></details>

**Comment by papaloredsxd** [comment]
Yes

**Comment by xBZZZZ** [comment]
<blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2025998274">Yes</blockquote>what is difference between:<ul><li>old gdccdated (642294321d01b6089ed70b4962bd98ded58e05db (before UTF-8 strict))</li><li>new gdccdated (e83b87fb6d64510efdb47aa247e27004cb1a4fa1) with <code>replace errors</code></li></ul>?

**Comment by papaloredsxd** [comment]
The old gdccdated is better, please downgrade the version of gdccdated to
this version right now
https://github.com/xBZZZZ/gdccdated/tree/7fc58401788a1e6d2b491a40e0a142113004a22b

**Comment by xBZZZZ** [comment]
<blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2027723348">The old gdccdated is better</blockquote>answer not useful, need more precise difference

**Comment by papaloredsxd** [comment]
I already told you

**Comment by xBZZZZ** [comment]
<blockquote cite="https://github.com/xBZZZZ/gdccdated/issues/4#issuecomment-2027907441">I already told you</blockquote>tell me again
